### PR TITLE
Update song list with new Splatoon™ soundtracks

### PR DESCRIPTION
**Pull request by mctaylors**
Changes in the list:
1. Fly Octo Fly ~ Ebb & Flow (Octo) / Off the Hook → Spectrum Obligato ~ Ebb & Flow (Out of Order) / Off the Hook feat. Dedf1sh
2. `#47` onward / Dedf1sh feat. Off the Hook
3. EchΘ Θnslaught / Free Association
4. Short Order / Off the Hook
5. Fins in the Air / Deep Cut

### CODE REVIEW

**Comment by Octol1ttle** [comment]
I thought we would leave the song list alone? Also, these soundtracks appear to come from Side Order, for which I'm trying to avoid all spoilers

**Comment by mctaylors** [comment]
> I thought we would leave the song list alone?

Well, I liked them, and Splatoon's music is expanding, and in fact I'll probably add a "track shuffle" feature (#265) soon, so...

> Also, these soundtracks appear to come from Side Order, for which I'm trying to avoid all spoilers

OK, I'll close the PR until you complete the Side Order so I don't spoil anything. No, like, really, I respect other people's interests *or what this thing called*.

**Comment by mctaylors** [comment]
No longer relevant. PR will be permanently closed.

**Comment by mctaylors** [comment]
> No longer relevant. PR will be permanently closed.

wdym
image

**Review by Octol1ttle — APPROVED** [review]
whateva', I don't really care about the song list

**Pull request merged**
