### PR TITLE
Redesign reminder-related commands

### PR DESCRIPTION
**Pull request by mctaylors**
In this PR, I redesigned the reminder-related commands and they will now have a quote block instead of a inline code block (to avoid some visual bugs). Except /listremind. It just has the inline code block removed.
image

### CODE REVIEW

**Comment by Octol1ttle** [comment]
I have the following concerns:
a) If we want to fight formatting abuse, we need to do it everywhere, not just in /remind
b) Wouldn't it be better to remove any offending characters automatically instead of having the user remove the characters?
c) Is it worth it fighting this? We can ignore this, there aren't any major issues caused by this. At the very least, we can just never use inline code blocks like we do in other places

**Comment by mctaylors** [comment]
> a) If we want to fight formatting abuse, we need to do it everywhere, not just in /remind

can you tell me where Octobot also shows user input in inline code block?

**Comment by Octol1ttle** [comment]
> can you tell me where Octobot also shows user input in inline code block?

Ctrl+Shift+F `.InlineCode(`

**Comment by mctaylors** [comment]
> > can you tell me where Octobot also shows user input in inline code block?
> 
> Ctrl+Shift+F `.InlineCode(`

Well, that doesn't seem quite right. The solution you propose affects all inline code blocks, not just _user input_ in the inline code blocks.

Anyway, since we didn't used inline code blocks in /ban, /mute, /kick commands, I'll just remove `.InlineCode()` things in reminder-related commands.

**Comment by mctaylors** [comment]
> Anyway, since we didn't used inline code blocks in /ban, /mute, /kick commands, I'll just remove `.InlineCode()` things in reminder-related commands.

Didn't like this idea either.

**Comment by Octol1ttle** [comment]
Please update your pull request description and provide new screenshots.

**Comment by mctaylors** [comment]
> Please update your pull request description and provide new screenshots.

Done. Sorry for the delay.

**Review by Octol1ttle — APPROVED** [review]

**Pull request merged**
