### PR TITLE
Add RepositoryAuthor and RepositoryName in BuildInfo

### PR DESCRIPTION
**Pull request by mctaylors**
#300 :partying_face:

Anyway, this PR add two new const strings named RepositoryAuthor and RepositoryName. This was made for future PR (which will be open in about 5-10 minutes).

### CODE REVIEW

**Comment by Octol1ttle** [comment]
If you need this just for #301, I would reject this because this solves very little use cases. What if the image isn't hosted on GitHub? What if the path to the image is different?
At this point, just put the whole link in a const, without any interpolation

**Comment by mctaylors** [comment]
> What if the path to the image is different?

...then what's stopping a developer from changing it as he pleases? 

> At this point, just put the whole link in a const, without any interpolation

Even if we declare const string for the logo:
1. we will still need to dynamically change the reference to the logo (for example: if the author/repository name changes)
2. it will again be a const string for a single use in /about. I just can't think of any other uses for it.

**Comment by Octol1ttle** [comment]
What is the point of this pull request? I thought that you added this here for developers to have an easier time changing the logo URL, but your own points seem to disprove that

**Comment by mctaylors** [comment]
> What is the point of this pull request? I thought that you added this here for developers to have an easier time changing the logo URL, but your own points seem to disprove that

Perhaps (if you insist) I will create a separate const string for the logo in BuildInfo, but I think RepositoryAuthor and RepositoryName will still be useful in some places.

**Comment by Octol1ttle** [comment]
In which places?

**Comment by mctaylors** [comment]
> In which places?

No _exact_ places yet, and I also have future plans for them.

**Comment by Octol1ttle** [comment]
In that case, please implement the changes when these "future plans" come.

**Pull request closed without merging**
